apiVersion: v1
data:
  config.yaml: |
    server:
      addr: :8080
      readTimeout: 120s
      writeTimeout: 120s
    mysql:
    - default:
        host: host
        port: 1234
        db: obnvmf
        user: user_xxx
        passwd: passwd_xxx
    clusterName: sigma-staging-cloud
    multiServices:
      test-k8s-cluster: http://node-disk-controller.svc.test-k8s-cluster.local:8080
kind: ConfigMap
metadata:
  name: webapi-config
  namespace: obnvmf