apiVersion: v1
kind: ConfigMap
metadata:
  name: storage-setting
  namespace: obnvmf
data:
  config.yaml: |
    scheduler:
      maxRemoteVolumeCount: 3
      filters:
      - Basic
      - Affinity
      - ObReplica
      - LocalWatermark
      priorities:
      - LeastResource
      - PositionAdvice
    pluginConfigs:
      defaultLocalSpaceRules:
        - enableDefault: true
          defaultLocalStoragePct: 100
          labelSelector:
            matchLabels:
              biz-name: cloudprovision
      autoAdjustLocal:
        enable: true
        maxCountInProcess: 1
        labelSelector:
          matchLabels:
            biz-name: cloudprovision
  agent-config.yaml: |
    storage:
      pooling:
        name: aio-lvs
        mode: SpdkLVStore
      bdev:
        type: aioBdev
        name: test-aio-bdev
        size: 1048576000 # 1GiB
        filePath: /local-storage/aio-lvs
