apiVersion: v1
kind: ConfigMap
metadata:
  name: storage-setting
  namespace: obnvmf
data:
  config.yaml: |
    scheduler:
      maxRemoteVolumeCount: 3
      minLocalStoragePct: 20
      filters:
      - Basic
      - Affinity
      - ObReplica
      - MinLocalStorage
      priorities:
      - LeastResource
      - PositionAdvice
      remoteIgnoreAnnoSelector:
        obnvmf/regard-as-remote: "false"
      lockSchedConfig:
        nodeSelector:
        - key: sigma.ali/lock-node
          operator: Exists
        nodeTaints:
        - key: node.sigma.ali/lifecycle
          operator: Exists
      #nodeReservations:
      #- id: obnvmf/app-vol
      #  size: 107374182400 # 100Gi
    pluginConfigs:
      defaultLocalSpaceRules:
        - enableDefault: true
          defaultLocalStoragePct: 100
          labelSelector:
            matchLabels:
              machine.sigma.alipay.com/biz-name: cloudprovision
      autoAdjustLocal:
        enable: true
        maxCountInProcess: 1
        labelSelector:
          matchLabels:
            machine.sigma.alipay.com/biz-name: cloudprovision
  agent-config.yaml: |
    storage:
      pooling:
        name: test-vg
        mode: KernelLVM
      pvs:
      - filePath: /local-storage/pv01
        size: 1048576000 # 1GiB